### ISSUE TITLE
meta: check permissions for api calls

### ISSUE THREAD

**Issue by bucherfa** [LAM-GeMont/fehlzeiten#138]
- [ ] absences
  - [x] createAbsences -> everyone
  - [ ] deleteAbsence -> teacher only self submitted that are not excuses, coordinator all
  - [ ] absence query -> teacher only self submitted or if teacher has the student in their tutorium, coordinator all
  - [ ] absences query -> teacher only self submitted or if teacher has the student in their tutorium, coordinator all
- [ ] excuses
  - [ ] excuse -> teacher only self submitted
  - [ ] createExcuse -> teacher for students that are in their tutorium, coordinator all
  - [ ] deleteExcuse (still to be implemented in #125) -> teacher only self submitted, coordinator all
- [x] students
  - [x] all queries -> everyone
  - [x] all mutations -> coordinator
- [x] semester
  - [x] all queries -> everyone
  - [x] all mutations -> coordinator
- [x] tutorium
  - [x] all queries -> everyone
  - [x] all mutations -> coordinator
- [ ] user
  - [x] register -> coordinator
  - [x] login -> unauthorized
  - [ ] logout -> everyone

cc: @jonaslanglotz @EricZimmer1
