### ISSUE TITLE
As a coordinator, I want to see a list of all tutoriums, to get an overview of which ones exist.

### ISSUE THREAD

**Issue by jonaslanglotz** [LAM-GeMont/fehlzeiten#31]
# Tasks

- [x] Create a tutorium page
- [x] Create a list view
- [x] Create a database table
- [x] Expose API queries to see the tutoriums
